task :default do
  begin
    require File.expand_path('../../lib/passenger_standalone/version', __FILE__)
    nginx_tarball_path = Dir[File.expand_path("../../src/nginx-*.tar.gz", __FILE__)].first
    STDERR.puts("Attempting to install Nginx from #{nginx_tarball_path}")
    vendor_path = File.expand_path('../../vendor/passenger', __FILE__)
    system('passenger',
           'package-runtime', vendor_path,
           '--nginx-tarball', nginx_tarball_path)
  rescue => e
    STDERR.puts("Error installing Nginx: #{e.class.name}: #{e.message}")
    raise
  end
end
